### ISSUE TITLE
Link to the official sources

### ISSUE THREAD

**Issue by AlCalzone** [LynxyssCZ/xiaomi-gap#1]
Hello,

I'm trying to build an integration for Xiaomi's BLE devices into my app. You write that your code is based on
> Sources used during this project are official Xiaomi MIOT documents available on their site

Any chance you could provice me with a link or the documents themselves? I couldn't find them sadly.

Thanks in advance.

**Comment by AlCalzone** [comment]
I guess not

**Comment by koalabz** [comment]
Maybe you can try this repo : https://github.com/MiEcosystem/mijia_ble

**Comment by koalabz** [comment]
> I guess not

Maybe you can try this repo : https://github.com/MiEcosystem/mijia_ble

Found : 
http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_pdf_f119c8464d43526b48fb453f19f30192.pdf

**Comment by AlCalzone** [comment]
Cool thank you! Although I can't read chinese, the pdf helps a bit.

**Comment by koalabz** [comment]
> Cool thank you! Although I can't read chinese, the pdf helps a bit.

Use google translate
